### ISSUE TITLE
Generic template image for ad boost trigger

### ISSUE THREAD

**Issue by shikhar1verma** [shikhar1verma/auto-eatventure#2]
Currently ad boost trigger have template image for 2x boost. If that present then ad boost happens. 

We need some generic solution so that no matter its user with 2x permanent boost or no boost all have same behaviour of triggering boost when its not present.

**Comment by sashaimba13** [comment]
if i change the template for my boost it ad-looping game :(

**Comment by shikhar1verma** [comment]
Sorry, to reply so late. Actually I was on holidays. 

I thought of a few tricks in which it can work but I didn't find any.

I'll try one more time today and will update you. Just needed a specific group of pixels which tells to boost the  game.

And the boost is run for 12 times because that's the number where the boost is on a full time period.

**Comment by shikhar1verma** [comment]
I have found the solution for non 2x permanent boost users to automatically do boost when required. Now the code will check yellow color pixels where the x2 boost shown under money.

@sashaimba13

**Comment by sashaimba13** [comment]
I just bought x2 perm boost and it working fine.
The recent problem is that in the beggining of every city it being stuck.
I come home and there's opened food upgrade button and it don't lvling up.

**Comment by shikhar1verma** [comment]
Ummm. Are you using the same emulator type that is written in readme. Because yesterday when I pushed my code. I checked it for an hour. And it moved to another city and the program was working fine.

Provide some more info like screenshot or some other info about emulator and app version.

If it's a problem that persists, we'll create another issue. But we first need more information regarding the problem so that we can accordingly solve it.

**Comment by sashaimba13** [comment]
> Ummm. Are you using the same emulator type that is written in readme. Because yesterday when I pushed my code. I checked it for an hour. And it moved to another city and the program was working fine.
> 
> Provide some more info like screenshot or some other info about emulator and app version.
> 
> If it's a problem that persists, we'll create another issue. But we first need more information regarding the problem so that we can accordingly solve it.

I use latest android studio on windows
with settings given in readme

app version is 1.10.1

Okay, when i'll come home i'll make screnshots etc :)

**Comment by shikhar1verma** [comment]
> > Ummm. Are you using the same emulator type that is written in readme. Because yesterday when I pushed my code. I checked it for an hour. And it moved to another city and the program was working fine.
> > 
> > Provide some more info like screenshot or some other info about emulator and app version.
> > 
> > If it's a problem that persists, we'll create another issue. But we first need more information regarding the problem so that we can accordingly solve it.
> 
> I use latest android studio on windows
> with settings given in readme
> 
> app version is 1.10.1
> 
> Okay, when i'll come home i'll make screnshots etc :)

I think best is to create another issue for this problem and have this discussion there.
