### ISSUE TITLE
Issue when running script.

### ISSUE THREAD

**Issue by sashaimba13** [shikhar1verma/auto-eatventure#5]
I'm doing all as guide says.
But when I start script it does nothing. Only tracing coordinates of Eatventure.
I'm not a programmer at all and can't do in-depth analysis of it.
Would u kindly suggest what can i try?

UBUNTU 22.04
PYTHON 3.10
Android Studio (Pixel 6 pro)

**Comment by GenereicUsername** [comment]
Try with Python 3.7, the program is done in python 3.7

**Comment by sashaimba13** [comment]
![Снимок экрана от 2023-07-28 00-58-38](https://github.com/shikhar1verma/auto-eatventure/assets/140689400/75b61371-e108-4e95-820c-622384ed3830)

tried
nothing happens

**Comment by thiagoleal** [comment]
@sashaimba13 did you ever find a solution for this?

**Comment by sashaimba13** [comment]
> @sashaimba13 did you ever find a solution for this?

yes, but script is dead
too many thing were added with updates
plus eatventure don't work on emulator now (cloud functions)

**Comment by Anaocalvo** [comment]
> > @sashaimba13 did you ever find a solution for this?
> 
> yes, but script is dead too many thing were added with updates plus eatventure don't work on emulator now (cloud functions)

Could you send it anyway?Please, I'm trying to make it work in a physical device, so it surpasses the integrity problem, but i'm running into the same problem in emulator.
